image: evilsith/evildind:ojdk11-libcrypto

definitions:
  services:
    docker:
      memory: 2048

pipelines:
  default:
    - step:
        name: test
        services:
          - docker
        script:
          - export GRADLE_USER_HOME=`pwd`/gradle
          - export TESTCONTAINERS_RYUK_DISABLED=true
          - sh ./gradlew clean test -i
  branches:
    main:
      - step:
          name: deploy
          image: ruby:2.7.5
          deployment: heroku
          trigger: manual
          script:
            - gem install dpl
            - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
